language: java

jdk:
  - oraclejdk8

# force upgrade Java8 as per https://github.com/travis-ci/travis-ci/issues/4042 (fixes compilation issue)
addons:
  apt:
    packages:
      - oracle-java8-installer

# cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

before_install:
 - chmod +x gradlew